/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.airlinebooking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SYED IMRAN
 */
public class BookFlight extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddCustomer
     */
    public BookFlight() {
        initComponents();
        AutoId();
    }

    Connection con;
    PreparedStatement pre;

    public void AutoId() {
        try {
            Class.forName("com.mysql.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost/flight_booking", "root", "Shamshad@1");
            pre = con.prepareStatement("Select MAX(TicketId) from ticket");
            ResultSet rs = pre.executeQuery();
            rs.next();
            if (rs.getString("MAX(TicketId)") == null) {
                autoTicketId.setText("T001");
            } else {
                int idLast = Integer.parseInt(rs.getString("MAX(TicketId)").substring(1, rs.getString("MAX(TicketId)").length()));
                idLast++;
                autoTicketId.setText("T" + String.format("%03d", idLast));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField24 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        labelClassOfTravel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        selectClassOfTravel = new javax.swing.JComboBox<>();
        labelSeats = new javax.swing.JLabel();
        labelFair = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        priceCalculationBtn = new javax.swing.JButton();
        txtFair = new javax.swing.JTextField();
        labelTotalCost = new javax.swing.JLabel();
        customerDetails = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        labelFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        searchCustomerBtn = new javax.swing.JButton();
        labelPassportId = new javax.swing.JLabel();
        txtPassportId = new javax.swing.JTextField();
        flightDetails = new javax.swing.JLabel();
        labelCustomerId = new javax.swing.JLabel();
        selectSeat = new javax.swing.JSpinner();
        labelFlightId = new javax.swing.JLabel();
        labelFligthName = new javax.swing.JLabel();
        labelArrivalTime = new javax.swing.JLabel();
        txtFlightName = new javax.swing.JTextField();
        txtFlightId = new javax.swing.JTextField();
        txtDuration = new javax.swing.JTextField();
        txtArrivalTime = new javax.swing.JTextField();
        labelDuration = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFlightData = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        labelArrival = new javax.swing.JLabel();
        selectArrival = new javax.swing.JComboBox<>();
        labelDeparture = new javax.swing.JLabel();
        selectDeparture = new javax.swing.JComboBox<>();
        labelDot = new javax.swing.JLabel();
        searchFlightBtn = new javax.swing.JButton();
        selectDot = new com.toedter.calendar.JDateChooser();
        labelTicketId = new javax.swing.JLabel();
        autoTicketId = new javax.swing.JLabel();
        bookFlightBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setClosable(true);

        labelClassOfTravel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelClassOfTravel.setText("Class Of Travel");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        selectClassOfTravel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"select Class", "Economic", "Business", "First" }));

        labelSeats.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelSeats.setText("No. Of Seats");

        labelFair.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelFair.setText("Charge");

        priceCalculationBtn.setText("Calculate");
        priceCalculationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceCalculationBtnActionPerformed(evt);
            }
        });

        labelTotalCost.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelTotalCost.setText("Total Fair");

        customerDetails.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        customerDetails.setText("Customer Details");

        txtFirstName.setCaretColor(new java.awt.Color(255, 0, 0));

        labelFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFirstName.setText("First name");

        labelLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelLastName.setText("Last name");

        searchCustomerBtn.setText("Search");
        searchCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerBtnjButton4ActionPerformed(evt);
            }
        });

        labelPassportId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPassportId.setText("Passport Id");

        flightDetails.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        flightDetails.setText("Flight Details");

        labelCustomerId.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelCustomerId.setText("Search Customer");

        labelFlightId.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelFlightId.setText("Flight Id");

        labelFligthName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelFligthName.setText("Flight Name");

        labelArrivalTime.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelArrivalTime.setText("Arrival Time");

        txtFlightName.setCaretColor(new java.awt.Color(255, 0, 0));

        txtFlightId.setCaretColor(new java.awt.Color(255, 0, 0));

        txtDuration.setCaretColor(new java.awt.Color(255, 0, 0));

        txtArrivalTime.setCaretColor(new java.awt.Color(255, 0, 0));

        labelDuration.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelDuration.setText("Duration");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(customerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(labelCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(labelFirstName)
                                        .addComponent(labelLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(labelPassportId, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassportId, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFlightId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFligthName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFlightId, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelClassOfTravel)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelArrivalTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelFair))
                                            .addComponent(labelDuration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelSeats))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selectSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(selectClassOfTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFair, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(labelTotalCost))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceCalculationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 23, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(flightDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(customerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPassportId)
                            .addComponent(txtPassportId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(flightDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFlightId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFlightId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFligthName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelClassOfTravel)
                                    .addComponent(selectClassOfTravel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelSeats)
                                    .addComponent(selectSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFair)
                            .addComponent(txtFair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTotalCost)
                            .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priceCalculationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        tabelFlightData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight Id", "Flight Name", "Arival", "Departure", "Date", "ArivTime", "Depart Time", "Duration", "Charge"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelFlightData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelFlightDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelFlightData);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        labelArrival.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelArrival.setText("Arrival");

        selectArrival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select", "Mumbai", "Bangalore", "Delhi", "Kolkata", "Chennai", }));

        labelDeparture.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelDeparture.setText("Departure");

        selectDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mumbai", "Bangalore", "Delhi", "Kolkata", "Chennai",}));

        labelDot.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelDot.setText("Date Of Travel");

        searchFlightBtn.setText("Search");
        searchFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(selectArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(selectDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelArrival)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDeparture)
                        .addGap(94, 94, 94))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelDot)
                        .addGap(65, 65, 65)
                        .addComponent(selectDot, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(searchFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArrival)
                    .addComponent(labelDeparture))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDot, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectDot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(searchFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelTicketId.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        labelTicketId.setText("Ticket Id");

        autoTicketId.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        autoTicketId.setText("T.No");

        bookFlightBtn.setText("Book Flight");
        bookFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelTicketId, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(autoTicketId, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(bookFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelTicketId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(autoTicketId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(bookFlightBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            this.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //TicketId,Fname,Lname,Passport,FlightId,Flightname,Arrival,Departure,ArrivalTime,Duration,Travelclass,Seats,Charge
        
        try{
            String TID = autoTicketId.getText();
            String FN = txtFirstName.getText();
            String LN = txtLastName.getText();
            String custId = txtCustomerId.getText();
            String passport = txtPassportId.getText();
            String Arrival = selectArrival.getSelectedItem().toString();
            String Departure = selectDeparture.getSelectedItem().toString();     
            DateFormat df = new SimpleDateFormat("dd-MM-YYYY");
            String DOt = df.format(selectDot.getDate()); 
            String F = txtFlightName.getText();
            String FlightId = txtFlightId.getText();
            String Duration = txtDuration.getText();
            String Arrival_time = txtArrivalTime.getText();
            String CT=selectClassOfTravel.getSelectedItem().toString();
            String seats=selectSeat.getValue().toString();
            String charge = txtFair.getText();
            String totalCost = txtTotalPrice.getText();
        
         Class.forName("com.mysql.jdbc.Driver");
       
        con=DriverManager.getConnection("jdbc:mysql://localhost/flight_booking", "root", "Shamshad@1");
        pre=con.prepareStatement("Insert into ticket(TicketId,custId,Fname,Lname,Passport,FlightId,Flightname,TravelDate,Arrival,Departure,ArrivalTime,Duration,Travelclass,Seats,Charge, Total) value(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");   
        pre.setString(1, TID);  
        pre.setString(2, custId);  
        pre.setString(3, FN);
        pre.setString(4, LN);
        pre.setString(5, passport);
        pre.setString(6, FlightId);
        pre.setString(7, F);
        pre.setString(8, DOt);
        pre.setString(9, Arrival);
        pre.setString(10, Departure);
        pre.setString(11, Arrival_time );
        pre.setString(12, Duration);
        pre.setString(13, CT);
        pre.setString(14, seats);
        pre.setString(15, charge);
        pre.setString(16, totalCost);
        

        pre.executeUpdate();
        JOptionPane.showMessageDialog(null, "Flight Booked! Enjoy your Journey.....");
        
        AutoId();
        
            txtFirstName.setText("");
            txtLastName.setText("");
            txtCustomerId.setText("");
            txtPassportId.setText("");
            selectArrival.setSelectedItem(null);
            selectDeparture.setSelectedItem(null);
            selectDot.setDate(null);
            txtFlightName.setText("");
            txtFlightId.setText("");
            txtDuration.setText("");
            txtArrivalTime.setText("");
            selectClassOfTravel.setSelectedItem(null);
            selectSeat.setValue(null);
            txtFair.setText("");
            txtTotalPrice.setText("");
        
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchCustomerBtnjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerBtnjButton4ActionPerformed
        String custId = txtCustomerId.getText();
        try {

            Class.forName("com.mysql.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost/flight_booking", "root", "Shamshad@1");
            pre = con.prepareStatement("Select * from addcust where CustId=?");

            pre.setString(1, custId);

            ResultSet rs = pre.executeQuery();

            if (rs.next() == false) {
                JOptionPane.showMessageDialog(null, "Record not found");
                txtFirstName.setText("");
                txtLastName.setText("");
                txtCustomerId.setText("");
                txtPassportId.setText("");
            } else {

                String FN = rs.getString("Fname");
                String LN = rs.getString("Lname");
                String passport = rs.getString("PassportId");
                txtFirstName.setText(FN.trim());
                txtLastName.setText(LN.trim());
                txtPassportId.setText(passport.trim());
            }

            

        }catch (ClassNotFoundException ex) {Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchCustomerBtnjButton4ActionPerformed

    private void searchFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightBtnActionPerformed
       try {

            String Arrival = selectArrival.getSelectedItem().toString();
            String Departure = selectDeparture.getSelectedItem().toString();
           
            DateFormat df = new SimpleDateFormat("dd-MM-YYYY");
            String DOt = df.format(selectDot.getDate());

            if (Arrival.equalsIgnoreCase(Departure)) {
                JOptionPane.showMessageDialog(this, " Error Arrival and Departure are same ");
               
                selectArrival.setSelectedItem(null);
                
                selectDeparture.setSelectedItem(null);
                
                selectDot.setDate(null);
            } else {
                Class.forName("com.mysql.jdbc.Driver");

                con = DriverManager.getConnection("jdbc:mysql://localhost/flight_booking", "root", "Shamshad@1");
                pre = con.prepareStatement("Select * from addflight where Arival=? and Departure=? and TravelDate=?");
                
                pre.setString(1, Arrival);
                pre.setString(2, Departure);
                pre.setString(3, DOt);
                

                ResultSet rs=pre.executeQuery();
                ResultSetMetaData rsm=rs.getMetaData();
                
                int c=rsm.getColumnCount();
                
                DefaultTableModel DF=(DefaultTableModel)tabelFlightData.getModel();
                DF.setRowCount(0);
                
                while(rs.next()){
                    Vector v=new Vector();
                    for(int i=0;i<=c;i++){
                         
                        v.add(rs.getString("FlightId"));
                        v.add(rs.getString("Flight_name"));
                        v.add(rs.getString("Arival"));
                        v.add(rs.getString("Departure"));
                        v.add(rs.getString("TravelDate"));
                        v.add(rs.getString("ArrivalTime"));
                        v.add(rs.getString("DepartureTime"));
                        v.add(rs.getString("duration"));
                        v.add(rs.getString("charge"));
                    }
                    DF.addRow(v);
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_searchFlightBtnActionPerformed

    private void tabelFlightDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelFlightDataMouseClicked
       DefaultTableModel DF=(DefaultTableModel)tabelFlightData.getModel();
       int idx=tabelFlightData.getSelectedRow();
       
       txtFlightId.setText(DF.getValueAt(idx, 0).toString());
       txtFlightName.setText(DF.getValueAt(idx, 1).toString());
       txtDuration.setText(DF.getValueAt(idx, 7).toString());
       txtArrivalTime.setText(DF.getValueAt(idx, 5).toString());
       txtFair.setText(DF.getValueAt(idx, 8).toString());
    }//GEN-LAST:event_tabelFlightDataMouseClicked

    private void priceCalculationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceCalculationBtnActionPerformed
        int price=Integer.parseInt(txtFair.getText());
        String CT=selectClassOfTravel.getSelectedItem().toString();
        
        if(CT.equalsIgnoreCase("Economic")){
            price+=1500;
            txtFair.setText(String.valueOf(price));
        }else if(CT.equalsIgnoreCase("First")){
            price+=2200;
            txtFair.setText(String.valueOf(price));
        }
        int seats=Integer.parseInt(selectSeat.getValue().toString());
        
        int cost=price*seats;
        txtTotalPrice.setText(String.valueOf(cost));
    }//GEN-LAST:event_priceCalculationBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autoTicketId;
    private javax.swing.JButton bookFlightBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel customerDetails;
    private javax.swing.JLabel flightDetails;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JLabel labelArrival;
    private javax.swing.JLabel labelArrivalTime;
    private javax.swing.JLabel labelClassOfTravel;
    private javax.swing.JLabel labelCustomerId;
    private javax.swing.JLabel labelDeparture;
    private javax.swing.JLabel labelDot;
    private javax.swing.JLabel labelDuration;
    private javax.swing.JLabel labelFair;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelFlightId;
    private javax.swing.JLabel labelFligthName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelPassportId;
    private javax.swing.JLabel labelSeats;
    private javax.swing.JLabel labelTicketId;
    private javax.swing.JLabel labelTotalCost;
    private javax.swing.JButton priceCalculationBtn;
    private javax.swing.JButton searchCustomerBtn;
    private javax.swing.JButton searchFlightBtn;
    private javax.swing.JComboBox<String> selectArrival;
    private javax.swing.JComboBox<String> selectClassOfTravel;
    private javax.swing.JComboBox<String> selectDeparture;
    private com.toedter.calendar.JDateChooser selectDot;
    private javax.swing.JSpinner selectSeat;
    private javax.swing.JTable tabelFlightData;
    private javax.swing.JTextField txtArrivalTime;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtFair;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFlightId;
    private javax.swing.JTextField txtFlightName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassportId;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
